### ISSUE TITLE
Update Version of Elm from 0.17.0 -> 0.18.0

### ISSUE THREAD

**Issue by Rcsuax** [niksilver/elm-motion#1]
Hey I read your article on Elm on NikSilver.com which was really interesting,
Anyway I would like to contribute to this and upgrade it to use elm 0.18 if that would be okay?
Best,
Rcsua

**Comment by niksilver** [comment]
Hi there. The elm-motion project isn't one I'm maintaining at the moment. (In fact I'm that's true of all my coding projects right now). It would probably be better for you to fork it and update it yourself, and if you let me know then I can add a pointer that your version is more up to date.

**Comment by Rcsuax** [comment]
Wasn't really much work I just made the changes so i could run the example, I'm happy to create a fork or just to create a pull request and leave it at that :)

**Comment by niksilver** [comment]
I think it would be fairer to others if you forked it and I pointed to you (and deprecated mine by implication). That would indicate clearly that you're the maintainer of the latest version.

**Comment by Rcsuax** [comment]
Here is the link to fork: https://github.com/Rcsuax/elm-motion

**Comment by niksilver** [comment]
Great, thanks. I've updated my README to point to your repository. And thanks for taking the time to look my code and develop it further.
